# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temp.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntemp.proto\"9\n\nSumRequest\x12\x14\n\x0c\x66irst_number\x18\x01 \x01(\x05\x12\x15\n\rsecond_number\x18\x02 \x01(\x05\"\x1d\n\x0bSumResponse\x12\x0e\n\x06result\x18\x01 \x01(\x05\x32\x35\n\x11\x43\x61lculatorService\x12 \n\x03sum\x12\x0b.SumRequest\x1a\x0c.SumResponseB\x18\n\x14\x63om.proto.calculatorP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'temp_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\024com.proto.calculatorP\001'
  _globals['_SUMREQUEST']._serialized_start=14
  _globals['_SUMREQUEST']._serialized_end=71
  _globals['_SUMRESPONSE']._serialized_start=73
  _globals['_SUMRESPONSE']._serialized_end=102
  _globals['_CALCULATORSERVICE']._serialized_start=104
  _globals['_CALCULATORSERVICE']._serialized_end=157
# @@protoc_insertion_point(module_scope)
