// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: temp.proto

package com.proto.calculator;

public interface SumResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SumResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 result = 1;</code>
   */
  int getResult();
}
