// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: python_bridge.proto

package grpc.bridge.python;

public interface CommonResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CommonResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   */
  boolean getSuccess();
}
