// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: python_bridge.proto

package grpc.bridge.python;

public interface DriverDebugAddressRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DriverDebugAddressRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string ip = 1;</code>
   */
  java.lang.String getIp();
  /**
   * <code>string ip = 1;</code>
   */
  com.google.protobuf.ByteString
      getIpBytes();

  /**
   * <code>int32 port = 2;</code>
   */
  int getPort();
}
