// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: python_bridge.proto

package grpc.bridge.python;

public final class PythonBridgeOuterClass {
  private PythonBridgeOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SumRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SumRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SumResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SumResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DriverDebugAddressRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DriverDebugAddressRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CommonResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CommonResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023python_bridge.proto\"9\n\nSumRequest\022\024\n\014f" +
      "irst_number\030\001 \001(\005\022\025\n\rsecond_number\030\002 \001(\005" +
      "\"\035\n\013SumResponse\022\016\n\006result\030\001 \001(\005\"5\n\031Drive" +
      "rDebugAddressRequest\022\n\n\002ip\030\001 \001(\t\022\014\n\004port" +
      "\030\002 \001(\005\"!\n\016CommonResponse\022\017\n\007success\030\001 \001(" +
      "\0102O\n\014PythonBridge\022?\n\020resolveRecaptcha\022\032." +
      "DriverDebugAddressRequest\032\017.CommonRespon" +
      "seB\026\n\022grpc.bridge.pythonP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_SumRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SumRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SumRequest_descriptor,
        new java.lang.String[] { "FirstNumber", "SecondNumber", });
    internal_static_SumResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SumResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SumResponse_descriptor,
        new java.lang.String[] { "Result", });
    internal_static_DriverDebugAddressRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_DriverDebugAddressRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DriverDebugAddressRequest_descriptor,
        new java.lang.String[] { "Ip", "Port", });
    internal_static_CommonResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_CommonResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CommonResponse_descriptor,
        new java.lang.String[] { "Success", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
